import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/ibm-plex-sans";

export const metadata: Metadata = {
  title: "Knayf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  `}>{children}</body>
    </html>
  );
}
