import type { Metadata } from "next";
import "./[lang]/globals.css";
import "@fontsource-variable/ibm-plex-sans";
import Providers from "./providers";
// test
export const metadata: Metadata = {
  title: "market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="font-plex" lang="en" dir="ltr" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
