import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/ibm-plex-sans";
import { Locale } from "@/i18n.config";
import { Noto_Nastaliq_Urdu, Gulzar } from "next/font/google";
import DictionaryProvider from "@/dictionaries/DictionaryProvider";
import { getDictionary } from "@/utils/dictionary";

export const metadata: Metadata = {
  title: "market",
  description: "Generated by create next app",
};

const nastaliq = Noto_Nastaliq_Urdu({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const gulzar = Gulzar({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});
export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;

  const dictionary = await getDictionary(lang as Locale);

  return (
    <html className="font-plex" lang={lang} dir={lang === "en" ? "ltr" : "rtl"}>
      <body className={lang === "en" ? "" : gulzar.className}>
        <DictionaryProvider dictionary={dictionary}>
          {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
