import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/ibm-plex-sans";
import { Locale } from "@/i18n.config";

import DictionaryProvider from "@/dictionaries/DictionaryProvider";
import { getDictionary } from "@/utils/dictionary";
export const metadata: Metadata = {
  title: "market",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params; // ✅ Await params

  const dictionary = await getDictionary(lang);
  return (
    <html lang="en">
      <body className={`  `}>
        <DictionaryProvider dictionary={dictionary}>
          {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
