import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/ibm-plex-sans";
import { Locale } from "@/i18n.config";
import { Rubik, Noto_Nastaliq_Urdu } from "next/font/google";

import DictionaryProvider from "@/dictionaries/DictionaryProvider";
import { getDictionary } from "@/utils/dictionary";
export const metadata: Metadata = {
  title: "market",
  description: "Generated by create next app",
};
const nastaliq = Noto_Nastaliq_Urdu({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params; // ✅ Await params

  const dictionary = await getDictionary(lang);
  return (
    <html
      className={"font-plex"}
      lang={lang}
      dir={lang === "en" ? "ltr" : "rtl"}
    >
      <body className={`  `}>
        <DictionaryProvider dictionary={dictionary}>
          {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
